### ISSUE TITLE
Ignoring Attribute Server Spam

### ISSUE THREAD

**Issue by DeliciousTea** [ChaosBuffalo/MKUltra#130]
Not entirely sure what is causing this to happen. I've tried playing with MK Ultra alone and I see this at the beginning of the console log but it doesn't spam constantly in single player. On a server, however, with other mods, it spams the console every 20 seconds or so with multiple instances of:

9:19:13 PM
 CONSOLE:
[WARN] Ignoring unknown attribute 'generic.attackSpeed'

It happens so much that the log files actually bloat out of control. Before installing MK Ultra, this didn't happen. Hopefully that gives you some info to work with!

**Comment by Kovak** [comment]
Hi,

We're still looking for a fix for this one. It isn't necessarily harmful but it does spam the logs. It has to do with the fact that we introduce the attack speed attribute onto mobs. When they reload, they don't have attack speed so then the loading code posts this 'warning', to my knowledge there isn't quite a place to get ahold of them and fix it before that loading happens.

**Comment by DeliciousTea** [comment]
Okay, fabulous, I thought that was probably the issue, since it seemed to occur around mob spawning. 

Thanks as always, I really love this mod! The new stuff and bug fixes have been great!
