### ISSUE TITLE
Sudden crash with Special Mobs

### ISSUE THREAD

**Issue by TimeConqueror** [ChaosBuffalo/MKUltra#201]
So it randomly happens in world.
[crash-2019-10-12_23.14.04-server.txt](https://github.com/ChaosBuffalo/MKUltra/files/3721119/crash-2019-10-12_23.14.04-server.txt)

**Comment by Kovak** [comment]
if you add  specialmobs:brutezombie to the attack speed whitelist in the mk config (called NPC Attack Speed Recipients in config) this should go away, but we are also working on a fix to prevent it in the future.

**Comment by Kovak** [comment]
A fix for this went out in .99.7
