### ISSUE TITLE
Brawler Stun and dynamic tree crash game

### ISSUE THREAD

**Issue by zongitgud** [ChaosBuffalo/MKUltra#206]
When use Brawler 4th skill, the aoe stun, it some how affect the tree from dynamic tree and cause crash
Here the crash log

**********
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2019-10-22 18:04:56 ICT
Description: Error executing task

java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Exception while adding particle
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: net.minecraft.util.ReportedException: Exception while adding particle
    at net.minecraft.client.renderer.RenderGlobal.spawnParticle(RenderGlobal.java:3015)
    at net.minecraft.client.renderer.RenderGlobal.spawnParticle(RenderGlobal.java:2988)
    at com.ferreusveritas.dynamictrees.event.BlockBreakAnimationClientHandler$RenderGlobalWrapper.spawnParticle(BlockBreakAnimationClientHandler.java:271)
    at net.minecraft.world.World.spawnParticle(World.java:1169)
    at net.minecraft.world.World.spawnParticle(World.java:1148)
    at com.chaosbuffalo.mkultra.fx.ParticleEffects.spawnParticleEffect(ParticleEffects.java:32)
    at com.chaosbuffalo.mkultra.network.packets.ParticleEffectSpawnPacket$Handler.handleClientMessage(ParticleEffectSpawnPacket.java:113)
    at com.chaosbuffalo.mkultra.network.packets.ParticleEffectSpawnPacket$Handler.handleClientMessage(ParticleEffectSpawnPacket.java:107)
    at com.chaosbuffalo.mkultra.network.MessageHandler.lambda$runHandleClient$0(MessageHandler.java:23)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at net.minecraft.client.particle.ParticleFallingDust$Factory.createParticle(SourceFile:81)
    at net.minecraft.client.particle.ParticleManager.spawnEffectParticle(ParticleManager.java:151)
    at net.minecraft.client.renderer.RenderGlobal.spawnParticle0(RenderGlobal.java:3110)
    at net.minecraft.client.renderer.RenderGlobal.spawnParticle(RenderGlobal.java:2995)
    ... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_231, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2259337368 bytes (2154 MB) / 5335154688 bytes (5088 MB) up to 5335154688 bytes (5088 MB)
  JVM Flags: 14 total; -Xmn128M -Xmx5081M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseG1GC -Xms1G -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 83 mods loaded, 83 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                            | Version                 | Source                                                   | Signature                                |
       |:------ |:----------------------------- |:----------------------- |:-------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                     | 1.12.2                  | minecraft.jar                                            | None                                     |
       | LCHIJA | mcp                           | 9.42                    | minecraft.jar                                            | None                                     |
       | LCHIJA | FML                           | 8.0.99.99               | forge-1.12.2-14.23.5.2847.jar                            | None                                     |
       | LCHIJA | forge                         | 14.23.5.2847            | forge-1.12.2-14.23.5.2847.jar                            | None                                     |
       | LCHIJA | creativecoredummy             | 1.0.0                   | minecraft.jar                                            | None                                     |
       | LCHIJA | itemphysic                    | 1.4.0                   | minecraft.jar                                            | None                                     |
       | LCHIJA | ivtoolkit                     | 1.3.3-1.12              | minecraft.jar                                            | None                                     |
       | LCHIJA | foamfixcore                   | 7.7.4                   | minecraft.jar                                            | None                                     |
       | LCHIJA | dsurroundcore                 | 3.5.5.0                 | minecraft.jar                                            | None                                     |
       | LCHIJA | randompatches                 | 1.12.2-1.19.1.1         | randompatches-1.12.2-1.19.1.1.jar                        | None                                     |
       | LCHIJA | adminshop                     | 1.0                     | adminshop-1.4.jar                                        | None                                     |
       | LCHIJA | alcatrazcore                  | 1.0.4                   | alcatrazcore-1.0.4.jar                                   | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
       | LCHIJA | biomesoplenty                 | 7.0.1.2441              | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar            | None                                     |
       | LCHIJA | craftstudioapi                | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar                    | None                                     |
       | LCHIJA | harvestcraft                  | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zf.jar                          | None                                     |
       | LCHIJA | animania                      | 1.7.2                   | animania-1.12.2-1.7.2.jar                                | None                                     |
       | LCHIJA | applecore                     | 3.2.0                   | AppleCore-mc1.12.2-3.2.0.jar                             | None                                     |
       | LCHIJA | baubles                       | 1.5.2                   | Baubles-1.12-1.5.2.jar                                   | None                                     |
       | LCHIJA | betterbuilderswands           | 0.11.1                  | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar          | None                                     |
       | LCHIJA | betterhud                     | 1.4.1                   | betterhud-1.12.2-1.4.1.jar                               | None                                     |
       | LCHIJA | bibliocraft                   | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                        | None                                     |
       | LCHIJA | chunkanimator                 | 1.2                     | ChunkAnimator-MC1.12-1.2.jar                             | None                                     |
       | LCHIJA | clans                         | 1.3.7                   | Clans-1.12.2-1.3.7.jar                                   | None                                     |
       | LCHIJA | clumps                        | 3.1.2                   | Clumps-3.1.2.jar                                         | None                                     |
       | LCHIJA | combatrefined                 | 1.4.1                   | combatrefined-1.4.1.jar                                  | None                                     |
       | LCHIJA | extendedrenderer              | v1.0                    | coroutil-1.12.1-1.2.31.jar                               | None                                     |
       | LCHIJA | coroutil                      | 1.12.1-1.2.31           | coroutil-1.12.1-1.2.31.jar                               | None                                     |
       | LCHIJA | configmod                     | v1.0                    | coroutil-1.12.1-1.2.31.jar                               | None                                     |
       | LCHIJA | creativecore                  | 1.9.9                   | CreativeCore_v1.9.62_mc1.12.2.jar                        | None                                     |
       | LCHIJA | customspawner                 | 3.11.4                  | CustomMobSpawner-1.12.2.jar                              | None                                     |
       | LCHIJA | customnpcs                    | 1.12                    | CustomNPCs_1.12.2-(01Oct19).jar                          | None                                     |
       | LCHIJA | cxlibrary                     | 1.6.1                   | cxlibrary-1.12.1-1.6.1.jar                               | None                                     |
       | LCHIJA | disenchanter                  | 1.6                     | disenchanter-[1.12]1.6.jar                               | None                                     |
       | LCHIJA | dldungeonsjbg                 | 1.12.10                 | DoomlikeDungeons-1.12.10-MC1.12.2.jar                    | None                                     |
       | LCHIJA | ebwizardry                    | 4.2.5                   | ElectroblobsWizardry-4.2.5-MC1.12.2.jar                  | None                                     |
       | LCHIJA | patchouli                     | 1.0-19                  | Patchouli-1.0-19.jar                                     | None                                     |
       | LCHIJA | mmorpg                        | 1.8.2                   | Mine+and+Slash-1.12.2-1.8.2.jar                          | None                                     |
       | LCHIJA | rcraft                        | 2.0.5                   | dotHack+Weapons-2.0.5.jar                                | None                                     |
       | LCHIJA | mocreatures                   | 12.0.5                  | DrZharksMoCreaturesMod-12.0.5.jar                        | None                                     |
       | LCHIJA | dungeondq                     | 10.00                   | DungeonDQ_Ver10.00_[MC1.12](forge-1.12-14.21.1.2387).jar | None                                     |
       | LCHIJA | dungeonmobs                   | 5.8.4                   | dungeonmobs-5.8.4-MC1.12.2.jar                           | None                                     |
       | LCHIJA | dynamictrees                  | 1.12.2-0.9.5            | DynamicTrees-1.12.2-0.9.5.jar                            | None                                     |
       | LCHIJA | dynamictreesbop               | 1.12.2-1.4.1e           | DynamicTreesBOP-1.12.2-1.4.1e.jar                        | None                                     |
       | LCHIJA | dynamictreesphc               | 1.12.2-1.4.2            | DynamicTreesPHC-1.12.2-1.4.2.jar                         | None                                     |
       | LCHIJA | enhancedvisuals               | 1.0                     | EnhancedVisuals_v1.2.6_mc1.12.2.jar                      | None                                     |
       | LCHIJA | epicsiegemod                  | 13.165                  | EpicSiegeMod-13.165.jar                                  | None                                     |
       | LCHIJA | foamfix                       | 0.10.7-1.12.2           | foamfix-0.10.7-1.12.2.jar                                | None                                     |
       | LCHIJA | grimoireofgaia                | 1.6.9.3                 | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                       | None                                     |
       | LCHIJA | hammercore                    | 2.0.5.2                 | HammerCore-1.12.2-2.0.5.2.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | llibrary                      | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                    | 1.8.2                   | iceandfire-1.8.2.jar                                     | None                                     |
       | LCHIJA | improvableskills              | 65r                     | ImprovableSkills-1.12.2-65r.jar                          | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | infernalmobs                  | 1.7.6                   | InfernalMobs-1.12.2.jar                                  | None                                     |
       | LCHIJA | infinity                      | 0.13.2                  | Infinity-0.13.2.jar                                      | None                                     |
       | LCHIJA | jei                           | 4.15.0.268              | jei_1.12.2-4.15.0.268.jar                                | None                                     |
       | LCHIJA | lycanitesmobs                 | 2.0.0.12 - MC 1.12.2    | lycanitesmobs-1.12.2-2.0.0.12.jar                        | None                                     |
       | LCHIJA | targeting_api                 | 0.15                    | targeting_api-0.15.jar                                   | None                                     |
       | LCHIJA | mkultra                       | 0.99.6                  | MKUltra-0.99.6.jar                                       | None                                     |
       | LCHIJA | mobends                       | 0.24                    | mobends-0.24_for_MC-1.12.jar                             | None                                     |
       | LCHIJA | mowziesmobs                   | 1.5.4                   | mowziesmobs-1.5.4.jar                                    | None                                     |
       | LCHIJA | nutrition                     | 4.4.0                   | Nutrition-1.12.2-4.4.0.jar                               | None                                     |
       | LCHIJA | potioncore                    | 1.8_for_1.12.2          | PotionCore-1.8_for_1.12.2.jar                            | None                                     |
       | LCHIJA | qualitytools                  | 1.0.7_for_1.12.2        | QualityTools-1.0.7_for_1.12.2.jar                        | None                                     |
       | LCHIJA | reccomplex                    | 1.4.8.2                 | RecurrentComplex-1.4.8.2.jar                             | None                                     |
       | LCHIJA | sereneseasons                 | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar                | None                                     |
       | LCHIJA | spawnercontrol                | 1.6.3b                  | SpawnerControl-1.6.3b.jar                                | None                                     |
       | LCHIJA | surge                         | 2.0.77                  | Surge-1.12.2-2.0.77.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tektopia                      | 1.1.0                   | tektopia-1.1.0.jar                                       | None                                     |
       | LCHIJA | thutessentials                | 2.2.23                  | thutessentials-1.12.2-2.2.23.jar                         | None                                     |
       | LCHIJA | vanillafix                    | 1.0.10-SNAPSHOT         | VanillaFix-1.0.10-99.jar                                 | None                                     |
       | LCHIJA | variedcommodities             | 1.12.2                  | VariedCommodities_1.12.2(15may18.jar                     | None                                     |
       | LCHIJA | wearablebackpacks             | 3.1.4                   | WearableBackpacks-1.12.2-3.1.4.jar                       | None                                     |
       | LCHIJA | weather2                      | 1.12.1-2.6.12           | weather2-1.12.1-2.6.12.jar                               | None                                     |
       | LCHIJA | roguelike_dungeons_remastered | 1.0.0                   | Wesley's+roguelike+dungeons.jar                          | None                                     |
       | LCHIJA | worleycaves                   | 1.5.1                   | worleycaves-1.5.1.jar                                    | None                                     |
       | LCHIJA | wowweapons                    | 0.0.8                   | WoWWeaponsMod-0.0.8.jar                                  | None                                     |
       | LCHIJA | wumpleutil                    | 2.12.6                  | wumpleutil-1.12.2-2.12.6.jar                             | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCHIJA | xaerominimap                  | 1.18.2                  | Xaeros_Minimap_1.18.2_Forge_1.12.jar                     | None                                     |
       | LCHIJA | xaeroworldmap                 | 1.4.10.1                | XaerosWorldMap_1.4.10.1_Forge_1.12.jar                   | None                                     |
       | LCHIJA | orelib                        | 3.5.2.3                 | OreLib-1.12.2-3.5.2.3.jar                                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                     | 3.5.5.0                 | DynamicSurroundings-1.12.2-3.5.5.0.jar                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | phosphor-lighting             | 1.12.2-0.2.6            | phosphor-1.12.2-0.2.6+build50-universal.jar              | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | hungeroverhaul                | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar               | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.7-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      HCASM (HammerCore-1.12.2-2.0.5.2.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      iceandfire (iceandfire-1.8.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.30' Renderer: 'GeForce GT 730/PCIe/SSE2'
  HammerCore Debug Information: Dependent Mods:
                                    -Improvable Skills (improvableskills) @65r
  Suspected Mods: Dynamic Trees (dynamictrees), MKUltra (mkultra)

**Comment by Kovak** [comment]
will look into a fix for this

**Comment by Kovak** [comment]
this should be fixed in .99.9+
