### ISSUE TITLE
Abilities don't trigger when bound to mouse buttons

### ISSUE THREAD

**Issue by notcake** [ChaosBuffalo/MKUltra#216]
**Version:** 0.99.11

`ClientKeyHandler` needs a `MouseInputEvent` handler that does the same thing as `onKeyEvent`

https://github.com/ChaosBuffalo/MKUltra/blob/master/src/main/java/com/chaosbuffalo/mkultra/event/ClientKeyHandler.java#L60

**Comment by Kovak** [comment]
Thank ya'll for finding and fixing this issues! Please consider opening a PR with the changes on your fork!

**Comment by notcake** [comment]
Looks like ralekdev has PR'd in a fix while we were distracted with modded minecraft. Thank you both for getting a fix into master!
