### ISSUE TITLE
Suggestion: Allow us to change spell damage values and durations in config?

### ISSUE THREAD

**Issue by jhth13rteen** [ChaosBuffalo/MKUltra#234]
As title says, I am not real keen on editing jar files and classes, so is there/will there be a way to edit things like levels, exp req'd to buy abilities, spell damage (nerfing or increasing) spell effects and durations? Such as editing the duration for HoT's or mana regen? So that we can fully customize balance and difficulty depending on what mods we use in our packs? Reason I ask this, if we have a pack that gives lots of EXP for tough mobs, its extremely easy to cap out abilities...etc, so having the player to grind more or put more effort in achieving cap would be beneficial than them just getting to cap in say, the first day.

Also, if you need sound effects, I can supply some sound effects for spells that was taken from the (now defunct) game Asheron's Call. Just let me know.

**Comment by jhth13rteen** [comment]
I'll give some context. For instance, in my pack I run first aid and rough tweaks. I also have natural regeneration turned off. This pack focuses on self healing, much in the same vein that RLCraft does with regard to bandages... etc. This mod effectively breaks that and since I had no need to use bandages, which largely makes First AId and Rough Tweaks null and void. What I would like is to be able to either nerf healing (put long cooldown, adjust the healing amount) or remove it entirely in order to maintain balance. Disabling entire spells like the (druid flight which is easily gotten) would be an extreme bonus as well. Also, as a side note - it would be prudent to give Brine Wizards underwater breathing or some form of staying underwater longer since, you know - they are Water Wizards. Also giving fire wizards Fire Resistance 1 or lava walking or something like that would be cool too. Of course these could be disabled in a config if someone wanted to customize that.

Furthermore, about the passives - how to activate them? Are they in the mod yet or is this a planned feature thats NYI?

Thanks for taking the time to read my walls of text and I appreciate any feedback! <3

**Comment by Kovak** [comment]
Hey,

I'm looking into configurable spell data for our 1.15 version. Passives are in the game, once you have put talent points into passives you should be able to select them on right side of the abilities screen below the player stat readout. There is a box you can click that will bring up a dropdown to choose your passive from.

It is possible to disable certain classes or change which classes have which abilities at the moment. All the json config that is in the jar can be placed in an mk_overrides folder in your config folder using the same paths and those values will override the default in the mod jar.

**Comment by jhth13rteen** [comment]
> I'm looking into configurable spell data for our 1.15 version.

Any chance for this feature to make into the 1.12 version also?

**Comment by Kovak** [comment]
No chance on 1.12, the solution we're working on relies on the datapack infrastructure.

**Comment by jhth13rteen** [comment]
kk
