### ISSUE TITLE
Server error. Not freezing, but maybe repairable. 

### ISSUE THREAD

**Issue by Taknax** [ChaosBuffalo/MKUltra#235]
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData
18.06 16:22:32 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.player.EntityPlayer from class com.chaosbuffalo.mkultra.core.PlayerData

**Comment by Taknax** [comment]
Sry if i post it wrong. Its my first issue post.

**Comment by Kovak** [comment]
This is not an issue. Just a warning because of a somewhat atypical use of part of minecraft. It will be gone in future versions as after 1.12 we don't use EntityDataManager like this anymore anyway.

Thanks for reporting though!
