### ISSUE TITLE
Integration Error with Lycanites Mobs Crashes Server Instantly

### ISSUE THREAD

**Issue by EaiteSuper** [ChaosBuffalo/MKUltra#236]
I was recently setting up a server for a friend's modpack. The modpack runs fine client-side and on LAN servers, but we decided we needed a bit of an upgrade. Every time I run the server, however, the server runs into a NoClassDefFoundError exception that force closes it. I was wondering if this is an issue pertaining more to MKUltra or Lycanites and whether or not I can salvage the modpack containing both mods.

Attached is my latest crash log.
[crash-2020-06-19_04.10.06-server.txt](https://github.com/ChaosBuffalo/MKUltra/files/4803345/crash-2020-06-19_04.10.06-server.txt)

**Comment by Kovak** [comment]
You would need to downgrade to an older version of lycanites. This has got to do with MKUltraX lycanites integration being built for an older version of lycanites. This error means lycanite move/rename one of his classes so the 2 mods no longer can talk together.
