### ISSUE TITLE
MKUltra Skills cannot be used on a sponge server

### ISSUE THREAD

**Issue by luenlin** [ChaosBuffalo/MKUltra#69]
SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3383
Forge version: 14.23.4.2705
Java version: 1.8.0_1.7.2
OS：windows server 2016
Plugins/Mods:
Minecraft,
Minecraft Forge,
SpongeAPI,
MKUltra-0.76 https://github.com/ChaosBuffalo/MKUltra
targeting_api-0.12 https://github.com/ChaosBuffalo/TargetingAPI
Issue Description
Some of the professional skills are not working properly on the Sponge Server.
For example, Druid's Ball Lightning and Flame Blade, Phoenix Aspect.
The specific performance is that the potion effect cannot be correctly given.
It should be said that most of the buff skills are invalid.

It should be said that it is not a potion buff invalid. It is simply not a player's potion effect.

**Comment by Kovak** [comment]
We are following up with this on the github for Sponge https://github.com/SpongePowered/SpongeForge/issues/2374
